<?php

namespace app\common\model;

use think\Model;

class Fangjian extends Model
{
	protected $name = "fangjian";
	
	protected function initialize ()
	{
		parent::initialize (); // TODO: Change the autogenerated stub
	}
}
