<?php

namespace app\common\model;

use think\Model;

class User extends Model {
	protected $name = "userlist";
	
	protected function initialize ()
	{
		parent::initialize (); // TODO: Change the autogenerated stub
	}
	
	/**
	 * 关联group表
	 * @return \think\model\relation\BelongsTo
	 */
	public function ugroup ()
	{
		return $this->belongsTo ('Group', 'group', 'groupid');
	}
	
	/**
	 * 关联房间表
	 * @return \think\model\relation\BelongsTo
	 */
	public function fangjian ()
	{
		return $this->belongsTo ('Fangjian', 'fid', 'fid');
	}
	
	/**
	 * 创建一个游客账号
	 *
	 * @param $group 用户组信息
	 * @param $fid   房间号
	 * @param $ip    登陆ip
	 *
	 * @return array|bool
	 */
	public function make_youke ($group, $fid, $ip)
	{
		$data = [
			'username' => "游客" . sprintf ("%'06s", mt_rand ('100000', '999999')),
			'group' => 3,
			'fid' => $fid,
			'registime' => time (),
			'loginip' => $ip,
			'isshui' => 0,
			'lasttime' => time (),
			'cansay' => $group[ 'cansay' ],
		];
		$r = $this->save ($data);
		if ( $r ) {
			$data[ 'id' ] = $this->id;
			$data[ 'islogin' ] = 0;
			$data[ 'groupname' ] = $group[ 'groupname' ];
			$data[ 'image' ] = str_replace ("\\", "/", $group[ 'image' ]);
			
			return $data;
		} else {
			return FALSE;
		}
	}
	
	/**
	 * 登陆验证
	 *
	 * @param $username 用户名
	 * @param $password 密码
	 * @param $fid      房间号
	 *
	 * @return array|false|\PDOStatement|string|Model
	 */
	public function check_login ($username, $password, $fid)
	{
		$where[ 'username' ] = $username;
		$where[ 'fid' ] = $fid;
		$where[ 'canlogin' ] = 1;
		/* 获取用户数据 */
		$user = $this->where ($where)->find ();
		if ( $user ) {
			if ( $user->password != md5 ($password) ) {
				$this->error = "登陆密码错误";
				
				return FALSE;
			} else {
				return $user->toArray ();
			}
		} else {
			$this->error = "用户名不存在或账户被禁止登录";
			
			return FALSE;
		}
	}
}
